#+TITLE: Departure Times Norway
#+AUTHOR: Henrik Solgaard
#+OPTIONS: toc:nil

* Overview

~departure-times-norway~ is an Emacs package that displays public transport departure times in Norway.

* Installation

** Using MELPA (the package is not available from MELPA yet!)

1. Ensure MELPA is added to your package archives:

   #+begin_src emacs-lisp
   (require 'package)
   (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
   (package-initialize)
   #+end_src

2. Install ~departure-times-norway~:

   #+begin_src emacs-lisp
   (package-install 'departure-times-norway)
   #+end_src

** Using Doom Emacs

Add ~departure-times-norway~ to your ~packages.el~:

#+begin_src emacs-lisp
(package! departure-times-norway :recipe (:host github :repo "hsolg/emacs-departure-times-norway"))
#+end_src

Then run:

#+begin_src shell
doom sync
#+end_src

Restart Emacs or run ~M-x doom/reload~.

Configure the package:

#+begin_src emacs-lisp
(use-package! departure-times-norway
  :commands (departure-times-norway-show-departures)
  :init
  ;; Add key binding (optional)
  (map! :leader
        :desc "Show departure times"
        "z d" #'departure-times-norway-show-departures)

  ;; Use Vim motions in the departure times buffer (optional)
  (with-eval-after-load 'evil
    (evil-set-initial-state 'departure-times-norway-mode 'motion)))
#+end_src

* Usage

The command departure-times-norway-show-departures displays the next
departures from a public transport stop. The first time the command
is invoked, it will display a search prompt in the minibuffer. The
next time it is invoked, it will remember the previous selection. To
select a new stop, invoke the command with a prefix argument (typically
C-u) to display the search prompt again.

* License

GPL-3+
